apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-admin-server
  labels:
    app: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: admin-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8086