apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  type: NodePort
  ports: 
    - name: gateway-port
      port: 8090
      targetPort: 8090
      nodePort: 30090