apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  type: NodePort
  ports: 
    - name: admin-port
      port: 8086
      targetPort: 8086
      nodePort: 30086